version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: constructora
      POSTGRES_USER: clean
      POSTGRES_PASSWORD: clean123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clean -d constructora"]
      interval: 10s
      timeout: 5s
      retries: 5
